### ISSUE TITLE
New Error </3 

### ISSUE THREAD

**Issue by Joolian1** [podaboutlist/linkfix-for-discord#43]
![image (2)](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/1eca428d-a432-4d08-b918-3469b2dbc11e)
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/c852e7f6-d2d9-4c19-a665-d80dfd241a5e)
![image](https://github.com/podaboutlist/linkfix-for-discord/assets/73612835/7c4ccbe7-88b7-4f5f-9099-6f80a6597db5) 

The NODE PACKAGES added automatically by the bot .

i convert the index.ts code to index.js into the src folder .. 

- i can give you admin access to see the code, etc . i can text u in discord if y want .

**Comment by RalphORama** [comment]
Like I said in the previous issue, the problem is with whatever software you are using to try and host the bot, not with LinkFix. We aren't going to provide support for any issue you have trying to set up LinkFix with this software. 

Please do not create any more issues about these types of problems.
