### ISSUE TITLE
Reddit: Galleries and YAGPDB (suggestions)

### ISSUE THREAD

**Issue by fbalt5** [podaboutlist/linkfix-for-discord#48]
Hi - I have two suggestions/requests to improve reddit embeds

First, I noticed that vxreddit only embeds the first photo of a gallery into discord. Switching to [rxddit.com](https://github.com/MinnDevelopment/fxreddit) may solve this as it embeds all photos in a gallery into discord

Second, I noticed that linkfix does not respond to reddit links sent by bots/webhooks. Allowing the bot to fix bot/webhook links would be useful since discord bots like YAGPDB send links directly to reddit, which breaks video embedding. Allowing users to toggle whether bots/webhook links are fixed could be useful

**Comment by RalphORama** [comment]
I'll check out `rxddit.com` as a replacement for `vxreddit.com`, thanks for the heads up about that.

As for replying to bots, that interaction is disabled to prevent infinite loops of bots replying to each other. I will see if there's anything I can do about YAGPDB but I don't think that will get implemented because it has massive potential to cause headaches.

Thank you for your suggestions!

**Comment by RalphORama** [comment]
I've updated the bot to use `rxddit.com` links instead of vxreddit. Unfortunately there's not a good way to implement YAGPDB support currently. I looked into it and there's a few edge cases that could cause infinite reply loops which would be hard to work around. Thank you for your suggestions!
