### ISSUE TITLE
[Feature Request] twitch clips

### ISSUE THREAD

**Issue by QarthO** [podaboutlist/linkfix-for-discord#79]
Support for twitch clips!

**Comment by RalphORama** [comment]
Do you know of a service that supports twitch clips? I.e. we use `fxtwitter` for twitter links, is there an equivalent?

**Comment by shoegaze** [comment]
Looks like there aren't any solutions at the moment, but Discord should support simple video clips already: Trying `https://www.twitch.tv/gooffkings/clip/{CLIP_ID}` and `https://clips.twitch.tv/embed?clip={CLIP_ID}` both work in vanilla discord.

I don't think interactive clips (those with live streams+chat, i.e. iframes) can work with discord since there are certain restrictions on the content of embeds (https://discord.com/safety/using-webhooks-and-embeds#title-4).

Are there any cases where the above aren't sufficient?
